---
title: "Data essay project"
output:
  pdf_document: default
---

# Intro

## Data description

Variables included:

**Dependent variable**

-   *citation*

The variable *citation_5yr_diff_circ_2022* indicates the number of times a certain judicial decision made by a judge was cited in following decisions by other judges in the five years following the initial decision.

**Main independent variables**

-   *female*

Var characteristics:

The variable *femaleOA* is a dummy variable and indicates if the judge of the case was male (0) or female (1). Looking at the values contained in the database, it is possible to observe that there are 2045 male judges and 637 female judges.

-   *minority*

The variable *OAminority* is a dummy variable and indicates if the judge of the case was white (0) or non-white (1). Looking at the values contained in the database, it is possible to observe that there are 2426 white judges and 478 non-white judges.

Var characteristics

**Control variables**



-   *authorities_deep*



-   *OAls_elite*



-   *OAtenure_ln*



## Summary statistics

-   Plot **citation**
    -   by *gender*?
    -   by *ethnicity*?
-   

# Analysis

Inluce the note at the end of *01 model.R* in the text here

The code fits two models—a Poisson regression (m1) and a Negative Binomial regression (m2)—to count data (citation) with predictors (female, minority, and their interaction). The Poisson model assumes the mean equals the variance, while the Negative Binomial model allows for overdispersion (variance > mean). Log-likelihoods of the two models (L1 and L2) are compared using a Likelihood Ratio Test (LRT), with the test statistic following a chi-squared distribution with 1 degree of freedom. The null hypothesis (H0) is that the Poisson model is sufficient, while the alternative (H1) suggests the Negative Binomial provides a better fit. If LRT > qchisq(0.95, df = 1) evaluates to TRUE, H0 is rejected, indicating significant overdispersion and the superiority of the Negative Binomial model.

### Hypothesis 1

### Hypothesis 2

### Hypothesis 3

# Simulation (aka scenario)

### Hypothesis 1

-   Intercept: 1
-   Female: 1
-   Minority: 1
-   Authorities: median
-   Elite: median
-   Tenure: median
-   Interaction: 1*1

Compare

-   Intercept: 1
-   Female: 0
-   Minority: 0
-   Authorities: median
-   Elite: median
-   Tenure: median
-   Interaction: 0*0

### Hypothesis 2

-   Intercept: 1
-   Female: 1
-   Minority: 1
-   Authorities: median
-   Elite: median
-   Tenure: median
-   Interaction: 1*1

Compare

-   Intercept: 1
-   Female: 1
-   Minority: 0
-   Authorities: median
-   Elite: median
-   Tenure: median
-   Interaction: 1*0

### Hypothesis 3

-   Intercept: 1
-   Female: 1
-   Minority: 1
-   Authorities: median
-   Elite: median
-   Tenure: median
-   Interaction: 1*1

Compare

-   Intercept: 1
-   Female: 0
-   Minority: 1
-   Authorities: median
-   Elite: median
-   Tenure: median
-   Interaction: 0*1

# Robustness check



# Conclusion


